### ISSUE TITLE
Checkout

### ISSUE THREAD

**Issue by Mary123987** [Mary123987/JAM-BITES#10]
![Image](https://github.com/user-attachments/assets/85b50d81-7184-4016-b834-f833101ab06d)

![Image](https://github.com/user-attachments/assets/bfaf79b8-3fc0-4f1d-86b5-231751ffa5ee)

**Comment by jimrv** [comment]
![Image](https://github.com/user-attachments/assets/6784c4a7-6ff1-48a8-85e7-a9fb99f6cd24)
visualizacion en la pagina
