### ISSUE TITLE
Crear cuenta

### ISSUE THREAD

**Issue by Mary123987** [Mary123987/JAM-BITES#5]

**Comment by jimrv** [comment]
![image](https://github.com/user-attachments/assets/01c5576c-61cc-441a-b5ab-7b54b45a92d2)
![image](https://github.com/user-attachments/assets/8a58f772-6cbe-47ec-8059-16154bf6ccaa)

**Comment by jimrv** [comment]
![image](https://github.com/user-attachments/assets/8a58f772-6cbe-47ec-8059-16154bf6ccaa)
